init Self-made Calculator
bewisesh91/HTML-CSS_practice pull request #1
Opened 2020-11-04 15:24 UTC by bewisesh91

Day_1

2020-11-04 15:31 UTC, HyunSangHan requested changes
일단, 창 너비를 아이폰 너비인 375px로 했을 때 아래와 같이 짜부러지네요.

![image](https://user-images.githubusercontent.com/44132406/98131004-3682cb80-1efe-11eb-9bb6-daf2f8b0606d.png)

2020-11-04 15:36 UTC, HyunSangHan commented
### git 및 github관련
1. 브랜치명은 `branch_1`처럼 무의미하게 지으면 안됩니다. `develop/calculator-test` 또는 `feature/add-calculator-frame` 이런 형태로 짓는 게 관행입니다.
2. PR의 제목과 내용도 충실하게 적어주셔야 합니다.
3. commit은 작업 단위로 쪼개어 여러번 남기는 게 좋습니다. 지금처럼 한덩어리로 커밋을 찍으면 히스토리 관리가 어렵고, 코드를 다시 과거로 되돌리고 싶을 때 그 중간으로 되돌아갈 수 없습니다. 커밋이 최소 단위라서요.
4. 그리고 저랑 경일님을 이 레포지토리의 Collaborator로 추가해주세요.(추가하는 방법은 구글링 또는 경일님께 문의)

2020-11-04 15:41 UTC, HyunSangHan reviewed
아래는, 사소하긴 하지만 코딩습관과 관련된 리뷰입니다.

2020-11-04 15:41 UTC, HyunSangHan commented on index.css
> +    height: 100px ;
```suggestion
    height: 100px;
```

2020-11-04 15:41 UTC, HyunSangHan commented on index.css
> +    border : 1px lightslategray solid;
```suggestion
    border: 1px lightslategray solid;
```

2020-11-04 15:41 UTC, HyunSangHan commented on index.css
> +    background-color: white ;
```suggestion
    background-color: white;
```

2020-11-04 15:41 UTC, HyunSangHan commented on index.css
> +    background-color: whitesmoke
```suggestion
    background-color: whitesmoke;
```

2020-11-04 15:41 UTC, HyunSangHan commented on index.html
> +            <div class="hori">
이건 그냥 예시로 적었던 거고, 원래 의미있는 이름을 지어야 합니다.

2020-11-04 15:41 UTC, HyunSangHan commented on index.html
> +                <div class="input_button number">7</div>
보통 class명을 snake_case는 쓰지 않습니다. `input-button` 일단 이런식으로 씁시다.

[참고] snake case란? http://guswnsxodlf.github.io/camelcase-pascalcase-snakecase

2020-11-04 15:41 UTC, HyunSangHan commented on index.html
> +<head>
html 태그의 자식으로 head와 body가 있는건데, 들여쓰기가 안되어있네요.

2020-11-04 15:47 UTC, HyunSangHan requested changes

2020-11-04 15:47 UTC, HyunSangHan commented on index.css
> +    width: 30%;
https://github.com/bewisesh91/HTML-CSS_practice/pull/1#pullrequestreview-523474745 에서 짜부러진다고 했던 건, 제가 테스트해본 결과 이 `#container`에서 padding, margin, width를 모두 지우니 해결되네요.

아래는 그 결과입니다.

![image](https://user-images.githubusercontent.com/44132406/98132620-f9b7d400-1eff-11eb-9896-940a4b264ca5.png)

지금 승현님 짜신 코드 보면, 계산기 컨테이너 너비는 고작 전체 너비의 30%밖에 안되고, 마진과 패딩은 300px과 50px로 고정인 상태죠.
창 너비를 줄임에 따라 컨테이너는 점점 줄어들텐데 마진/패딩은 고정값이니 상대적으로 여백의 비율이 점점 커졌던 겁니다. 그래서 너비를 모바일너비로 줄였을 때 거의 여백만 나도 나머지(컨테이너)는 짜부러져 보이는 거였습니다.

2020-11-04 15:51 UTC, HyunSangHan commented
아래 경일님한테 달아둔 코드리뷰 내용들도 참고해주세요.

https://github.com/justakim12/simple_projects_withJavaScript/pull/2#pullrequestreview-521722044

2020-11-04 15:53 UTC, HyunSangHan commented on index.css
> +}
이것보다 더 좋은 방법이 있는데..
영상에서 설명했던 `div 안의 자식 div`.. 라는 컨셉을 힌트로 해서 방법을 좀더고민해보세요.

2020-11-05 00:54 UTC, justakim12 commented
@HyunSangHan 
승현님 코드를 제 local에 다운받고 살펴볼 수 있게 세팅은 했는데요, 현상님이 위에서 하는것처럼 review는 어떻게 하죠? 코드를 일일이 markup으로 쓰신건 아닐거 같아서...제가 local에서 수정하고 commit하면 review처럼 나오는건가요?

2020-11-05 01:02 UTC, HyunSangHan commented
> 승현님 코드를 제 local에 다운받고 살펴볼 수 있게 세팅은 했는데요, 현상님이 위에서 하는것처럼 review는 어떻게 하죠? 코드를 일일이 markup으로 쓰신건 아닐거 같아서...제가 local에서 수정하고 commit하면 review처럼 나오는건가요?

아래와 같이 File changes라는 탭을 누르면 코드가 쫙 나옵니다.
![image](https://user-images.githubusercontent.com/44132406/98184468-d3b92080-1f4d-11eb-896e-f3554f11952d.png)
그중에 특정 코드가 적혀있는 라인을 누르면 코드리뷰를 할 수 있는 input 박스가 펼쳐지고요.

2020-11-05 12:38 UTC, justakim12 commented on index.html
> +
코드 리뷰 테스트 해봅니다!

2020-11-06 03:10 UTC, merged